HCIMSp/HCIMSp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from users import views
from django.conf import settings
from django.conf.urls.static import static
from HCIMS import views as hci_views
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', hci_views.index, name='home'),
    url(r'^patientsignup/', views.patientsignup, name='patientsignup'),
    url(r'^doctorsignup/', views.doctorsignup, name='doctorsignup'),
    url(r'^history/', views.history, name='history'),
    # url(r'^register/', views.register, name='register'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^history/', views.history, name='history'),
    url(r'^pricing/', views.pricing, name='pricing'),
    url(r'^doctor/', views.doctor, name='Mypatients'),
    url(r'^contact/', views.emailView, name='contact'),
    url(r'^success/', views.successView, name='success'),
    url(r'^api/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HCIMSp/users/urls.py
from django.conf.urls import include
from rest_framework import routers
from . import views
from django.conf.urls import url

router = routers.DefaultRouter()
router.register(r'history', views.HistoryViewSet)

urlpatterns = [
    url(r'', include(router.urls)),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

HCIMSp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.models import User
from PIL import Image
import datetime
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class User(AbstractUser):
    is_patient = models.BooleanField('patient status', default=False)
    is_doctor = models.BooleanField('doctor status', default=False)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', null=True)
        
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField(max_length=30, default="yours@gmail.com")
    phone_number = PhoneNumberField()
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')), blank=True)
    allergy = models.CharField(max_length=180, default="yours@gmail.com")
    blood_type = models.CharField(max_length=3, default="yours@gmail.com")
    height = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    blood_pressure = models.IntegerField(default=0)
    bmi_levels = models.IntegerField(default=0)
    temperature = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super(Patient, self).save(*args, **kwargs)

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', null=True)
    email = models.EmailField(max_length=30, default="yours@gmail.com")
    phone_number = models.IntegerField(default=0)
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')), blank=True)
    specialization = models.CharField(max_length=60, default="doctor")

    def __str__(self):
        return self.user.username

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
        
class History(models.Model):
    patient_history = models.ForeignKey(to=Patient, null=True, blank=True,on_delete=models.CASCADE)
    user = models.CharField(max_length=180)
    date = models.DateField(("Date"), default=datetime.date.today)
    time = models.TimeField(auto_now=False, auto_now_add=False, null=True)
    doctor = models.ForeignKey(to=Doctor, null=True, blank=True,on_delete=models.CASCADE)
    tests = models.CharField(max_length=360, default='NONE')
    drugs = models.CharField(max_length=360, default='none')
    consultation_cost = models.IntegerField(default=0)
    drugs_cost = models.IntegerField(default=0)
    labs_cost = models.IntegerField(default=0)
    total_cost = models.IntegerField(default=0)

    def __str__(self):
        return self.patient_history.user.username

HCIMSp/users/forms.py
from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Patient, Doctor, User
from django.db import transaction


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
        ]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'image',
        ]

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class PatientsignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

    @transaction.atomic
    def save(self):
        user = super(PatientsignupForm, self).save(commit=False)
        user.is_patient = True
        user.save()
        patient = Patient.objects.create(user=user)
        return user

class DoctorsignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

    @transaction.atomic
    def save(self):
        user = super(DoctorsignupForm, self).save(commit=False)
        user.is_doctor = True
        user.save()
        doctor = Doctor.objects.create(user=user)
        return user

HCIMSp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Patient, History, Doctor
from rest_framework import viewsets
from .serializers import HistorySerializer
import requests
from .forms import ContactForm, PatientsignupForm, DoctorsignupForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .decorators import group_required
# Create your views here.

# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             # messages.success(request, 'Account created!! Now log in')
#             return redirect('login')
#     else:
#         form = UserRegisterForm()
#     return render(request, 'users/register.html',{'form': form})
    
def patientsignup(request):
    if request.method == 'POST':
        form = PatientsignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            
            def get_context_data(self, **kwargs):
                kwargs['user_type'] = 'patient'
                return super().get_context_data(**kwargs)
            messages.success(request, 'Account created!! Now log in')
            return redirect('login')
    else:
        messages.success(request, 'Error')
        form = PatientsignupForm()
    return render(request, 'users/patientregister.html',{'form': form})

def doctorsignup(request):
    if request.method == 'POST':
        form = DoctorsignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            def get_context_data(self,**kwargs):
                kwargs['user_type'] = 'doctor'
                return super().get_context_data(**kwargs)
            # messages.success(request, 'Account created!! Now log in')
            return redirect('login')
    else:
        messages.success(request, 'Error')
        form = DoctorsignupForm()
    return render(request, 'users/doctorregister.html',{'form': form})

@login_required
def profile(request):
    patients = Patient.objects.all()
    patient_filter = patients.filter(user=request.user)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Account updated, now login')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'filter': patient_filter,
    }
    return render(request, 'users/profile.html', context)

@login_required
def history(request):
    history = History.objects.all()
    history_filter = history.filter(user=request.user)
    history_docfilter = Doctor.objects.filter(history__user=request.user)
    context = {
        'history_filter': history_filter,
        'history_docfilter':history_docfilter
    }
    return render(request, 'HCIMS/history.html', context)

@login_required
def pricing(request):
    price = History.objects.all()
    price_filter = price.filter(user=request.user)
    context = {
        'price_filter': price_filter,
    }
    return render(request, 'HCIMS/pricing.html', context)

class HistoryViewSet(viewsets.ModelViewSet):
    queryset = History.objects.all().order_by('user')
    serializer_class = HistorySerializer
    def get_queryset(self):
        if self.action == 'list':
            return self.queryset.filter(user=self.request.user)
        return self.queryset

@login_required
@group_required('doctor')
def doctor(request):
    doctor = Doctor.objects.all()
    doctor_filter = doctor.filter(user=request.user)
    history = History.objects.filter(doctor__user=request.user)
    patient = Patient.objects.all()
    context = {
        'doctor_filter': doctor_filter,
        'history': history,
        'patient': patient
    }
    return render(request, 'HCIMS/doctor.html', context)

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['collinshillary1@gmail.com'], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "HCIMS/contact.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you,,Your appointment request has been sent, You will receive a feedback within 6 hours.')

# def feedView(request):
#     # Init
#     newsapi = NewsApiClient(api_key='667065c36c064053be40c247f1b195e0')

#     # /v2/top-headlines
#     top_headlines = newsapi.get_top_headlines(q='bitcoin',
#                                             sources='bbc-news,the-verge',
#                                             category='business',
#                                             language='en',
#                                             country='us')

#     # /v2/everything
#     all_articles = newsapi.get_everything(q='bitcoin',
#                                         sources='bbc-news,the-verge',
#                                         domains='bbc.co.uk,techcrunch.com',
#                                         from_param='2017-12-01',
#                                         to='2017-12-12',
#                                         language='en',
#                                         sort_by='relevancy',
#                                         page=2)

#     # /v2/sources
#     sources = newsapi.get_sources()

#     context = {
#         'all_articles': all_articles,
#         'top_headlines': top_headlines
#     }
#     return render(request, 'HCIMS/index.html', context)

HCIMSp/users/templates/users/doctorregister.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HCIMS | Registration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container" style="margin-top: 70px;">
        <h1>DOCTOR REGISTRATION</h1>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                        {{ error }}
                </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" autofocus="" required="" id="id_username" placeholder="Username">
              </div>
              <div class="form-group col-md-6">
                <label for="id_email">Email</label>
                <input type="email" name="email" required="" id="id_email" class="form-control" id="inputPassword4" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <label for="id_password1">Password</label>
              <input type="password" name="password1" required="" id="id_password1" class="form-control" placeholder="password">
            </div>
            <div class="form-group">
              <label for="id_password2">Confirm Password</label>
              <input type="password" class="form-control" name="password2" required="" id="id_password2" placeholder="confirm password">
            <!-- <span class="helptext">Enter the same password as before, for verification.</span> -->
            </div>
    
            <div class="form-group">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                  Agree to the terms and condition
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
<footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    </footer>
</html>

HCIMSp/users/templates/users/patientregister.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HCIMS | Registration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container" style="margin-top: 70px;">
        <h1>PATIENT REGISTRATION</h1>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                        {{ error }}
                </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" autofocus="" required="" id="id_username" placeholder="Username">
              </div>
              <div class="form-group col-md-6">
                <label for="id_email">Email</label>
                <input type="email" name="email" required="" id="id_email" class="form-control" id="inputPassword4" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <label for="id_password1">Password</label>
              <input type="password" name="password1" required="" id="id_password1" class="form-control" placeholder="password">
            </div>
            <div class="form-group">
              <label for="id_password2">Confirm Password</label>
              <input type="password" class="form-control" name="password2" required="" id="id_password2" placeholder="confirm password">
            <!-- <span class="helptext">Enter the same password as before, for verification.</span> -->
            </div>
    
            <div class="form-group">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                  Agree to the terms and condition
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
<footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    </footer>
</html>

HCIMSp/users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HCIMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'HCIMS/profile.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="{% static 'HCIMS/main.js'%}"></script>
    <!-- <script src="https://unpkg.com/vue"></script> -->
</head>
<body>
    <nav class="navbar navbar-inverse visible-xs">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="#">HCIMS</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'home' %}">Dashboard</a></li>
                <li><a href="{% url 'history' %}">History</a></li>
                <li><a href="{% url 'pricing' %}">Pricing</a></li>
                <li><a href="{% url 'contact' %}">Appointments</a></li>
                <br><br>
                <li><a href="{% url 'login' %}">Sign Out</a></li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid" >
        <div class="row content">
            <div class="col-sm-3 sidenav hidden-xs" >
              <!-- SIDEBAR USERPIC -->
              <div class="profile-userpic" style="padding-top: 20px;">
                <a href="{% url 'profile' %}"><img src="{{ user.profile.image.url }}" alt="Userprofile" class="avatar"></a>
                
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                <a href="{% url 'profile' %}"><div class="profile-usertitle-name">
                        <p>{{ user.username }}</p>
                        </div></a>
                    </div> 
            <ul class="nav nav-pills nav-stacked">
                <li class="active" style="padding-top: 43px;"><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span>  Dashboard</a></li>
                <li><a href="{% url 'history' %}" style="padding-top: 50px;"><span class="glyphicon glyphicon-time"></span>  History</a></li>
                <li><a href="{% url 'pricing' %}" style="padding-top: 50px;"><span class="glyphicon glyphicon-stats"></span>  Pricing</a></li>
                <li><a href="{% url 'contact' %}" style="padding-top: 50px;"><span class="glyphicon glyphicon-bullhorn"></span>  Appointments</a></li>
                <br><br><br><br>
                <li><a href="{% url 'login' %}" style="padding-top: 110px;"><span class="glyphicon glyphicon-log-out"></span>  Sign Out</a></li>
            </ul><br>
            </div>
            <!-- <div id="app">
                    <p> [[ title ]] </p>
                    <ul>
                        {% for day in days %}
                        <li>
                            <h4> Day [[ day ]]</h4>
                        </li>
                        {% endfor %}
                    </ul>
                </div> -->
            <div class="col-md-9">
                <div class="row" style="margin-top: 108px;margin-left: 40px;">
                    <div class="col-md-4">
                        <div class="card">
                            <img src="{{ user.profile.image.url }}" alt="Userprofile" style="width:100%">
                            <h1>{{ user.username }}</h1>
                            <div class="change">
                                    <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <p>
                                            <label for="id_username">Username:</label> 
                                            <input type="text" name="username" value="collins" required="" id="id_username" maxlength="150" style="color: white;">
                                            <!-- <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span> -->
                                        </p>
                                        <br>
                                        <br>
                                        <p>
                                            <label for="id_email">Email:</label> 
                                            <input type="email" name="email" value="collinshillary1@gmail.com" required="" id="id_email" style="color: white;">
                                        </p>
                                        <br>
                                        <br>
                                        <p>
                                            <!-- <label for="id_image">Image:</label> Currently: <a href="/media/profile_pics/doc4.jpg">profile_pics/doc4.jpg</a><br> -->
                                            Change Image:
                                            <input type="file" name="image" id="id_image" style="padding-left: 33px;padding-top: 23px;">
                                        </p>
                                        <br>
                                        <br>
                                        <button type="submit">Update</button>
                                    </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="w3-container">
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#general">General</a></li>
                                <li><a data-toggle="tab" href="#medical">Medical</a></li>
                            </ul>
                            
                            {% for i in filter %}
                            <div class="tab-content">
                                <div id="general" class="tab-pane fade in active">
                                    <br>
                                        <p>Name : {{user.username}} </p>
                                        <br>
                                        <p>Email : {{i.email}} </p>
                                        <br>
                                        <p>Phone Number : {{i.phone_number}} </p>
                                        <br>
                                        <p>Gender : {{i.gender}}</p>
                                        <br>
                                        <p>Allergy to drugs : {{i.allergy}} </p>
                                        <br>
                                </div>
                                <div id="medical" class="tab-pane fade">
                                    <br>
                                        <p>Blood Type : {{i.blood_type}} </p>
                                        <br>
                                        <p>Height : {{i.height}} Meters </p>
                                        <br>
                                        <p>Weight : {{i.weight}} Kg </p>
                                        <br>
                                        <p>Blood Pressure Level: {{i.blood_pressure}} mm/hg </p>
                                        <br>
                                        <p>BMI levels: {{i.bmi_levels}} </p>
                                        <br>
                                        <p>Temperature: {{i.temperature}} C </p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<footer>
        <!-- <script>
                new Vue({
                  delimiters: ['[[', ']]'],
                  el: '#app',
                  data: {
                    title: 'Welcome to My Journal'
                  }
                })
        </script> -->
    <script>
        AOS.init();
    </script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
</footer>
</html>